[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.42", features = ["serde"] }
anyhow = "1.0.99"
bimap = "0.6.3"
once_cell = "1.21.3"
serde_json = "1.0"